### ISSUE TITLE
Misc items to check

### ISSUE THREAD

**Issue by embuco** [thoufer/mbp-metadatacatalog#17]
1. GCJV assets are listed as R2 but contact is Steve DeMaso, R4 ... check these are correct [Becky]
2. Should R3 eagle nest DB be removed (is this ES asset)? [Becky]
3. Who is the contact in place of Carol Beardmore (retired) for the cooperative MX surveys ... ask Ken Kreise or Dave Olson about status of asset [Becky]
4. Ask Josh: (a) who is the primary contact for the Emperor Goose Spring and Fall Aerial surveys (Josh? Julian?); (b) confirm Josh is the primary contact for the trumpeter swan survey, (c) ask him to check all the goose surveys to make sure we have everything correct [Becky contact Josh]
5. Ask Debbie to check various R7 entries and provide corrections (or edit herself).  Ask who is the contact for the Central Arctic Survey ... Pam G? Debbie? other? [Emily]

**Comment by thoufer** [comment]
Split into individual issues.
