### ISSUE TITLE
Should R3 eagle nest DB be removed (is this ES asset)?

### ISSUE THREAD

**Issue by thoufer** [thoufer/mbp-metadatacatalog#21]
Should R3 eagle nest DB be removed (is this ES asset)?

**Comment by Rrau** [comment]
contacted Mags by email to get an update on database

**Comment by embuco** [comment]
I think her answer confirms that this is not a MigBirds asset (since she is looking for MigBirds help), so it seems to me it should be cut, unless and until we take on the effort of maintaining or storing these data ....

**Comment by thoufer** [comment]
If the decision is to cut this create an new issue assigned to me, then
close this with a comment referencing the issue to remove from DB.


---------------------------------------
US Fish and Wildlife Service
Division of Migratory Bird Management
11510 American Holly Dr.
Laurel MD 20708

301-497-5869 (phone)
301-497-5871 (fax)
https://www.fws.gov/birds

**Comment by embuco** [comment]
closed, Issue #60 assigned to Nate to cut from catalog
