### ISSUE TITLE
parental definition

### ISSUE THREAD

**Issue by embuco** [thoufer/mbp-metadatacatalog#46]
After conversation with Deb, I think we might want to revise all the parents that are also assets in and of themselves and change them so there is a list of children that combine under parent, but parent has no content of it's own .... that might make the keyword business easier, as the child asset names and keywords could ALL be listed under the parent and abstract could include the rationale for grouping.

In reviewing the list, that would only require a few assets to change.  She felt the Brant photo with Izembek under it was odd and would give R7 heartburn.  It might be better to have a consistent approach to what a parent is ...

**Comment by thoufer** [comment]
Closing as Parent/Child relation has been removed.
