### ISSUE TITLE
About catalog text

### ISSUE THREAD

**Issue by embuco** [thoufer/mbp-metadatacatalog#47]
"Data that are available from other USFWS programs or external partners will not be included, "

Deb brought up: what if we have given a copy of our data to someone else who is making it available, shouldn't it stay on our list?

Text here is a bit ambiguous.  I think "unless the data have been edited" is also ambiguous ... what data?

Discuss issue 1 and rephrase both 1 and 2.

**Comment by thoufer** [comment]
In the case of part one you say that *"if we have given a copy of OUR data"
.. *doesn't that imply that its an asset of our and on the list?   I think
the intent of the original statement is that this catalog only includes
assets of which the primary stewardship is the migratory bird program.  If
we have data from other programs, we should not be distributing it as we
are not the primary steward.. unless we are the data steward.  In that case
we are acting in a somewhat different capacity, I think.

I would agree with #2.

---------------------------------------
US Fish and Wildlife Service
Division of Migratory Bird Management
11510 American Holly Dr.
Laurel MD 20708

301-497-5869 (phone)
301-497-5871 (fax)
https://www.fws.gov/birds

**Comment by thoufer** [comment]
Closing as appears outdated.
