### ISSUE TITLE
Update About Page - MB Data Asset Catalog

### ISSUE THREAD

**Issue by Rrau** [thoufer/mbp-metadatacatalog#69]
Now that we have removed the parent asset from view we need to update the 'about page' when referring to sub-asset vs parent asset.  

https://www.migbirddatacatalog.us/about/

**Comment by embuco** [comment]
Please review this as a possible change to the current text:

_Data assets that are logically, logistically, or programmatically associated with one another are associated with the same project.  Assets within a project share a common history, administration, decision context, and/or species+location+platform.

Coordinating the management of related data assets is necessary for (i) effective data discoverability and integration (catalog goal #3), (ii) extending the usefulness of historical data, and (iii) ensuring the preservation of small-scale datasets. Identifying the governing project will enable efficient data governance and prioritization, and improve programmatic planning, resource allocation, and communication (catalog goals #1 and #2). Once a Programmatic governance structure is in place, a process for establishing appropriate relationships among data assets should be established._

**Comment by Rrau** [comment]
I think it sounds good.
