### ISSUE TITLE
update some About page text

### ISSUE THREAD

**Issue by embuco** [thoufer/mbp-metadatacatalog#72]
Can we replace the current About page text, paragraphs 1-2 with the following:

The Migratory Bird Program's Strategic Plan: 2018-28 includes "Manage Bird Data and Information" as one of the Program’s four primary goals. The first objective under this goal is to modernize our data management processes and establish a data governance structure.

A necessary step to meet this strategic goal will be the development of a comprehensive accounting of our data resources and assessment our data management capacity and needs. To aid this effort, the Migratory Bird Program (MBP) is developing a data catalog. The catalog is based on a preliminary data asset inventory that was compiled by the Migratory Bird Data Management Team through a program-wide survey. There are three primary purposes for this catalog:

**Comment by Rrau** [comment]
I see no reason why we can't update the text to this.  You need to put the word 'of' in between 'assessment' and 'our' in the first sentence of the second paragraph.

**Comment by embuco** [comment]
New text:

The Migratory Bird Program's Strategic Plan: 2018-28 includes "Manage Bird Data and Information" as one of the Program’s four primary goals. The first objective under this goal is to modernize our data management processes and establish a data governance structure.

A necessary step to meet this strategic goal will be the development of a comprehensive accounting of our data resources and assessment of our data management capacity and needs. To aid this effort, the Migratory Bird Program (MBP) is developing a data catalog. The catalog is based on a preliminary data asset inventory that was compiled by the Migratory Bird Data Management Team through a program-wide survey. There are three primary purposes for this catalog:
