### ISSUE TITLE
Partner Field Pull Request

### ISSUE THREAD

**Issue by Rrau** [thoufer/mbp-metadatacatalog#76]
Hi Nathan,

Would you be able to pull all the data out of the partner field and provide that to me in a compiled csv list or some other method that is easy for you?  I need to provide a list of all Mig Bird Program Partners to my Project Inventory Team to help populate our Partner field that will be a controlled hierarchical list similar to how PRIMR works.  I think we want to pull from their list as well as ours to get an idea of what partners we are already working with and then have a freeform feature that allows for additional Partners not already within the list.  We are also waiting on how the Policy team defines a Partner (e.g. how much effort, $ given, etc. constitutes a partner?)  I did provide my team with our definition of what defines a Partner.

**Comment by Rrau** [comment]
Secondly, were you aware that the Partner field has a limited number of characters?  It's small, so I advise that you expand the character limit.  Or maybe there was a reason we kept it small?  I can't include all of mine without using acronyms, which I don't want to do.

**Comment by thoufer** [comment]
The partner field has a 100 character limit..   Their may be another field type that may work better for this..   However, all changes are on pause until the longevity of they system has been addressed.
