### ISSUE TITLE
Delete 2 assets from Catalog

### ISSUE THREAD

**Issue by Rrau** [thoufer/mbp-metadatacatalog#89]
Nathan,

Please delete the following data assets from the catalog.  One now has data going directly into IMR (which, we already have here) and the other is not being maintained by MB.

Becky

Permitted Utility Project Mortality Surveys and Incidental Reporting - https://www.migbirddatacatalog.us/asset/detail/49/
(data goes directly into IMR now)

Construction Phase Nesting Bird Surveys & Monitoring - https://www.migbirddatacatalog.us/asset/detail/50/
(does not maintain data assets)

**Comment by thoufer** [comment]
Deleted
